language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_install:
  - echo "//artifactory.wikia-inc.com/artifactory/api/npm/wikia-npm/:_authToken=\${ARTIFACTORY_NPM_TOKEN}" >> .npmrc
  - cat .npmrc
script:
  - yarn
  - yarn ci
  - yarn coveralls
