module.exports = {
    outputDir: '.',
    styleguideDir: './docs',
    sourceDirectories: [
        'components',
        'hocs',
        'hooks',
        'models',
        'systems',
        'assets',
        'icons',
    ],
    sourceFiles: [
        'theme/breakpoints.js',
        'theme/colors.js',
        'theme/generateTheme.js',
        'theme/index.js',
        'theme/typography.js',
        'utils/eventLogger.js',
    ],
    externalDependencies: [
        'date-fns',
        // we ony use one function from date-fns
        'date-fns/distance_in_words_strict',
        'deepmerge',
        'i18next',
        'immutable',
        'prop-types',
        'react',
        'react-dom',
        'react-i18next',
        'react-redux',
        'react-select',
        'styled-components',
    ],
};
