const fs = require('fs');

const config = require('../config/config');

console.log('Building README files');

const autogeneratedReadme = `
Files in this directory are automatically re-generated. See the \`source\` directory in the root.
`;

config.sourceDirectories.forEach(
    directory => fs.writeFileSync(`${__dirname}/../../${directory}/README.md`, autogeneratedReadme)
);

const directories = config.sourceDirectories.map(
    directory => `* [${directory}](./${directory})`
).join('\n');

const rootReadme = `
# @Wikia/react-common

[![Travis](https://img.shields.io/travis/Wikia/react-common/master.svg?style=flat-square)](https://travis-ci.org/Wikia/react-common)
[![Release](https://img.shields.io/github/package-json/v/Wikia/react-common.svg?style=flat-square)](https://github.com/Wikia/react-common/releases)

Wikia's reusable React parts.

The following directories and files are auto-generated from the files in [source](./source) directory:

${directories}
* [docs](./docs)
* [README.md](./README.md)
* [package.json](./package.json)

Look in [source](./source) for details.
`;

fs.writeFileSync(`${__dirname}/../../README.md`, rootReadme);
